### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by bregman-arie** [LesConcepteursAssocies/briks#1]
How do you run it? whenever I try to run it on my Fedora I get:

Traceback (most recent call last):
  File "briks.py", line 246, in <module>
    main()
  File "briks.py", line 109, in main
    Config.bords = Border.Border()
  File "/home/abregman/dev/briks/Border.py", line 32, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)

**Comment by LesConcepteursAssocies** [comment]
Good morning.
Thank you for your return.
I'll look into it and let you know.
Sincerely,

**Comment by LesConcepteursAssocies** [comment]
Good morning,
The code as been developed ans tested on the following OS:
Linux Ubuntu 16.04.3 LTS (kernel 4.4.0-116) x64 (python 3.5.2 & pygame 1.9.3)
Windows 7 SP1 x64 (python 3.6.4 & pygame 1.9.3)

I modified the call to the init of the parent classes, you can download again and redo a test.
Sincerely,

**Comment by bregman-arie** [comment]
Thanks! works great now. The issue can be closed.
